from app.models.base import Base
from app.models.user import User
from app.models.department import Department
from app.models.faculty_profile import FacultyProfile
from app.models.publication import Publication
from app.models.education import Education
from app.models.experience import Experience
from app.models.project import Project
from app.models.achievement import Achievement
from app.models.patent import Patent
from app.models.certification import Certification
from app.models.teaching import Teaching
from app.models.student_guidance import StudentGuidance
