"""feat: add missing audit fields to experience and projects

Revision ID: 195d6919c1f7
Revises: 6f7a1a59cb66
Create Date: 2026-07-08 17:01:17.377134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "195d6919c1f7"
down_revision: Union[str, Sequence[str], None] = "6f7a1a59cb66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "experience", sa.Column("employment_type", sa.String(), nullable=True)
    )
    op.add_column("projects", sa.Column("team_members", sa.String(), nullable=True))
    op.add_column(
        "projects", sa.Column("project_documents_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "project_documents_url")
    op.drop_column("projects", "team_members")
    op.drop_column("experience", "employment_type")
    # ### end Alembic commands ###
