"""add_patents_and_certifications_fixed

Revision ID: 2f740d8904f1
Revises: 48ccab06c17f
Create Date: 2026-07-08 14:11:15.210096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f740d8904f1"
down_revision: Union[str, Sequence[str], None] = "48ccab06c17f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("faculty_profile_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("organization", sa.String(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("certificate_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["faculty_profile_id"], ["faculty_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_certifications_id"), "certifications", ["id"], unique=False
    )
    op.create_table(
        "patents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("faculty_profile_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("patent_number", sa.String(), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("FILED", "PUBLISHED", "GRANTED", "REJECTED", name="patentstatus"),
            nullable=False,
        ),
        sa.Column("inventors", sa.Text(), nullable=False),
        sa.Column("link_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["faculty_profile_id"], ["faculty_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patents_id"), "patents", ["id"], unique=False)
    op.create_index(
        op.f("ix_patents_patent_number"), "patents", ["patent_number"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patents_patent_number"), table_name="patents")
    op.drop_index(op.f("ix_patents_id"), table_name="patents")
    op.drop_table("patents")
    op.drop_index(op.f("ix_certifications_id"), table_name="certifications")
    op.drop_table("certifications")
    # ### end Alembic commands ###
