"""add_workshops_table

Revision ID: 3f4845ce82ec
Revises: 6f8676640706
Create Date: 2026-07-08 14:42:23.353161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3f4845ce82ec"
down_revision: Union[str, Sequence[str], None] = "6f8676640706"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workshops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("faculty_profile_id", sa.String(), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("organizer", sa.String(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("certificate_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["faculty_profile_id"], ["faculty_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workshops_id"), "workshops", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workshops_id"), table_name="workshops")
    op.drop_table("workshops")
    # ### end Alembic commands ###
