"""add_department_and_skills_to_profile

Revision ID: 5dd7fbb1372a
Revises: 3f4845ce82ec
Create Date: 2026-07-08 15:09:33.291985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5dd7fbb1372a"
down_revision: Union[str, Sequence[str], None] = "3f4845ce82ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "faculty_profiles", sa.Column("department", sa.String(), nullable=True)
    )
    op.add_column("faculty_profiles", sa.Column("skills", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("faculty_profiles", "skills")
    op.drop_column("faculty_profiles", "department")
    # ### end Alembic commands ###
