"""feat: add missing audit fields to publications

Revision ID: 6f7a1a59cb66
Revises: 9c54783c563d
Create Date: 2026-07-08 16:56:36.483097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6f7a1a59cb66"
down_revision: Union[str, Sequence[str], None] = "9c54783c563d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publications", sa.Column("authors", sa.String(), nullable=True))
    op.add_column("publications", sa.Column("journal", sa.String(), nullable=True))
    op.add_column("publications", sa.Column("issn", sa.String(), nullable=True))
    op.add_column("publications", sa.Column("indexed_in", sa.String(), nullable=True))
    op.add_column("publications", sa.Column("pdf_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publications", "pdf_url")
    op.drop_column("publications", "indexed_in")
    op.drop_column("publications", "issn")
    op.drop_column("publications", "journal")
    op.drop_column("publications", "authors")
    # ### end Alembic commands ###
