"""add_teaching_and_student_guidance

Revision ID: 6f8676640706
Revises: 2f740d8904f1
Create Date: 2026-07-08 14:31:27.100158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6f8676640706"
down_revision: Union[str, Sequence[str], None] = "2f740d8904f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_guidance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("faculty_profile_id", sa.String(), nullable=False),
        sa.Column("student_name", sa.String(), nullable=False),
        sa.Column("project_title", sa.String(), nullable=False),
        sa.Column("degree", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ONGOING", "COMPLETED", name="guidancestatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["faculty_profile_id"], ["faculty_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_student_guidance_id"), "student_guidance", ["id"], unique=False
    )
    op.create_table(
        "teaching",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("faculty_profile_id", sa.String(), nullable=False),
        sa.Column("course_name", sa.String(), nullable=False),
        sa.Column("subject_code", sa.String(), nullable=False),
        sa.Column("semester", sa.String(), nullable=False),
        sa.Column("academic_year", sa.String(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["faculty_profile_id"], ["faculty_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teaching_id"), "teaching", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teaching_id"), table_name="teaching")
    op.drop_table("teaching")
    op.drop_index(op.f("ix_student_guidance_id"), table_name="student_guidance")
    op.drop_table("student_guidance")
    # ### end Alembic commands ###
