"""feat: add missing audit fields to faculty profile

Revision ID: 9c54783c563d
Revises: 5dd7fbb1372a
Create Date: 2026-07-08 16:55:08.683674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9c54783c563d"
down_revision: Union[str, Sequence[str], None] = "5dd7fbb1372a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "faculty_profiles", sa.Column("employee_id", sa.String(), nullable=True)
    )
    op.add_column("faculty_profiles", sa.Column("website", sa.String(), nullable=True))
    op.add_column("faculty_profiles", sa.Column("linkedin", sa.String(), nullable=True))
    op.add_column(
        "faculty_profiles", sa.Column("google_scholar", sa.String(), nullable=True)
    )
    op.add_column("faculty_profiles", sa.Column("orcid", sa.String(), nullable=True))
    op.add_column(
        "faculty_profiles", sa.Column("office_location", sa.String(), nullable=True)
    )
    op.add_column(
        "faculty_profiles", sa.Column("specialization", sa.String(), nullable=True)
    )
    op.add_column(
        "faculty_profiles", sa.Column("areas_of_interest", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_faculty_profiles_employee_id"),
        "faculty_profiles",
        ["employee_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_faculty_profiles_employee_id"), table_name="faculty_profiles"
    )
    op.drop_column("faculty_profiles", "areas_of_interest")
    op.drop_column("faculty_profiles", "specialization")
    op.drop_column("faculty_profiles", "office_location")
    op.drop_column("faculty_profiles", "orcid")
    op.drop_column("faculty_profiles", "google_scholar")
    op.drop_column("faculty_profiles", "linkedin")
    op.drop_column("faculty_profiles", "website")
    op.drop_column("faculty_profiles", "employee_id")
    # ### end Alembic commands ###
